
clone_depth: 1

image:
  - Visual Studio 2013

platform:
  - x86

skip_commits:
  files:
    - '*.md'
    - docs/*
    - util/appveyor-mingw.yml
init:
  - ver
  - echo %PLATFORM%

install:
  - if %PLATFORM%==x86   call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\vcvars32.bat"
  - if %PLATFORM%==x86   set qt=5.6\msvc2013
before_build:
  - set QTDIR=C:\Qt\%qt%
  - set PATH=%PATH%;%QTDIR%\bin
  - qmake --version
build_script:
  - md build
  - cd build
  # with an additional flag NO_TESTS
  - qmake "..\pencil2d.pro" CONFIG+=GIT CONFIG+=Release CONFIG+=NO_TESTS CONFIG+=PENCIL2D_RELEASE CONFIG+=WIN_LEGACY VERSION=0.7.0
  - nmake
after_build:
  - set upload=yes
  - tree /f /a
  - powershell ..\util\after-build.ps1 -upload %upload% -platform x86 -branch %APPVEYOR_REPO_BRANCH%
test_script:
  - echo "No tests for VS2013"
  - tree /f /a

artifacts:
  - path: build/pencil2d-winxp.zip
